spring:
  application:
    name: lunar-oj
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev,local}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    com.lunaroj: INFO

lunaroj:
  init:
    root:
      enabled: ${ROOT_INIT_ENABLED:false}
      username: ${ROOT_INIT_USERNAME:root}
      password: ${ROOT_INIT_PASSWORD:dynamicCD+ACAM}
